### PR TITLE
Update to model unit values from telematics common enum

### PR DESCRIPTION
**Pull request by sureshven**

### CODE REVIEW

**Comment by agarwalashish** [comment]
Why do we need MetersPerSecondPerSecond, KilometersPerHourPerSecond and MilesPerHourPerSecond? We should try and stick to metric units - MetersPerSecond, KilometersPerHour and MilesPerHour as much as possible

**Comment by sureshven** [comment]
We should match the Mojio.TelematicServer Contract Enum Values. If we change it in the contracts then the SDK's should be updated to match. @nothingmn

**Comment by agarwalashish** [comment]
Is there a reason why we're using `public class LocationStatus` vs an `enum LocationStatus : String`

**Comment by sureshven** [comment]
> Is there a reason why we're using public class LocationStatus vs an enum LocationStatus : String

Swift (String) Enums are not visible in Objective C.

**Comment by agarwalashish** [comment]
MetersPerSecondPerSecond, KilometersPerHourPerSecond and MilesPerHourPerSecond are units of acceleration (I confused it them with units of speed for a moment). We should document that in the SDK as it is not very intuitive in the beginning.

**Comment by sureshven** [comment]
Sure - the Telematics Enums's are not well documented so we should start there for uniformity.

**Comment by agarwalashish** [comment]
Looks good.

**Pull request merged**
