### PR TITLE
Overhaul of Mojio SDK and conversion to iOS Framework

### PR DESCRIPTION
**Pull request by sureshven**
Updates to file layout of SDK project
Added Cocoapods support and build files

### CODE REVIEW

**Comment by agarwalashish** [comment]
Why are we using public dynamic var rather than dynamic var ? Given that the variables are "internal" by default, it should be fine. If we import the module into another module, internal should make the variable available to the other module

**Comment by agarwalashish** [comment]
Did we get a chance to run all the unit tests for the changes ?

**Comment by agarwalashish** [comment]
Is the intention to host the framework as a 'pod' or as a static library ?

**Comment by sureshven** [comment]
Is the intention to host the framework as a 'pod' or as a static library?

As a statically linkable framework (Bundle Type FMWK) that can be built from sources, or used from Cocoapods, Carthage, etc. iOS Frameworks can have their own images/assets and are easier for 3rd part developers to integrate.

**Comment by sureshven** [comment]
> Did we get a chance to run all the unit tests for the changes?

Yes - tests passed at 100% for the SDK.

**Comment by sureshven** [comment]
> Why are we using public dynamic var rather than dynamic var ? Given that the variables are "internal" by default, it should be fine. If we import the module into another module, internal should make the variable available to the other module

In order to access the SDK member values in the Framework from another Module you need public. There probably needs to be additional work to get the SDK to work with Objective-C apps.

_Public access enables entities to be used within any source file from their defining module, and also in a source file from another module that imports the defining module. You typically use public access when specifying the public interface to a framework._

**Comment by agarwalashish** [comment]
Wouldn't the command 

`import module`

make the variables accessible to classes that import the module ?

**Comment by sureshven** [comment]
> import module

No - by default a public Framework class var is private so you need an explicit qualifier.

_DashboardViewController.swift:197:20: error: value of type 'Vehicle' has no member 'VehicleLocation'
if vehicle.VehicleLocation != nil && vehicle.VehicleIgnitionState != nil {_

**Comment by agarwalashish** [comment]
Ok, then why not mark it as internal. That way it's only available to the classes that import it and not every class

**Comment by sureshven** [comment]
> Ok, then why not mark it as internal. That way it's only available to the classes that import it and not every class

You'll still have a visibility issue.

_Internal access enables entities to be used within any source file from their defining module, but not in any source file outside of that module. You typically use internal access when defining an app’s or a framework’s internal structure._

**Comment by agarwalashish** [comment]
Ok. Looks good then

**Pull request merged**
