### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by agarwalashish**

### CODE REVIEW

**Comment by skidson** [comment]
Is the "Pods" folder supposed to be included in version control? It looks like it contains each dependency's entire repo which doesn't seem like it should be nested in ours.

My guess is this is where dependencies are downloaded to based on the Podfile and each developer's machine would do this instead of getting them from version control?

**Comment by skidson** [comment]
Ok, can't actually view and comment on this diff on Github because it's past the file limit but here's some comments :stuck_out_tongue: 

* sdkv2.0.0/sdv2.0.0.0.xcodeproj/xcuserdata/Ashish.xcuserdatad - _seems like something that shouldn't be checked into source control?_
* AppDelegate.swift - _is this a sample app thing? I'm confused about it being in the sdk folder, unless it's something iOS requires for compilation. Same with the storyboards?_
* sdkv2.0.0/sdkv2.0.0/MojioSDK/ - might make sense to have model classes in a subfolder to distinguish easier between things like MojioClient, MojioAuth, JsonSerializer, etc
* MojioSDK/Vehicle - for TowState, ParkedState, AccidentState, HarshEventState, IdleState, and IgnitionState I found we could just have one "BooleanState" class for these as they all have the same structure
* MojioSDK - which model do you have for [VehicleMeasure](https://github.com/mojio/mojio-android-sdk/blob/develop/mojio-sdk-model/src/main/java/io/moj/mobile/android/sdk/model/VehicleMeasure.java)? (From /v2/vehicles/{id}/history/states) 
* MojioClientEnvironment - might be more in the spirit of OOP if this class was immutable (no setEnvironment function) and you pass an instance of it to MojioClient to configure it. In theory this would also let clients create multiple MojioClient instances to each hit a different environment if that was something they wanted to do. In Java my [Environment](https://github.com/mojio/mojio-android-sdk/blob/develop/mojio-sdk-common/src/main/java/io/moj/mobile/android/sdk/Environment.java) class is an enum - not sure if Swift enums have the same capabilities though

Final note - Swift is amazing, I can actually read it :smiley:

**Comment by agarwalashish** [comment]
Some good comments: 

• sdkv2.0.0/sdv2.0.0.0.xcodeproj/xcuserdata/Ashish.xcuserdatad should not be checked in. It is usually ignored by the .gitignore, but in this Swift project the ignore is not working. I plan on looking into that later.

• Yes. The project is structured so that there will be the SDK along with the sample project. When I put the SDK on Cocoapods, I will be able to select the files that I want part of the SDK and this will include only the SDK files. A good example of folder structure is the AFNetworking library: [https://github.com/AFNetworking/AFNetworking](url)

• Yes. I had sub-folders when I worked on the SDK as a submodule in the Motion project. They did not get copied over. I will look at it again.

• Good Idea. BooleanState makes more sense.

• Looks like I missed VehicleMeasure. Thanks for catching that.

• MojioClientEnvironment is a singleton. The developers can have as many instances of MojioClient as they need, but all of them will point to the same environment. They will set the environments using enums e.g. `MojioClientEnvironment.clientEnvironment.setEnvironment(Environment.AMERICA_STAGING)`

**Comment by skidson** [comment]
Cool. For the gitignore issue I know I've had issues in the past where updating it doesn't remove files that have already been committed. I look up this answer like every time to fix that: http://stackoverflow.com/a/11451731/2136792

So MojioClientEnvironment _is_ a singleton, but should it be? I don't see any requirement for it to be one.

**Comment by agarwalashish** [comment]
Made the following changes:

• Added a BooleanState class for TowState, ParkedState, AccidentState, HarshEventState, IdleState, and IgnitionState with a BooleanState

• Added the VehicleMeasures class and unit tests for it

• Added a sub-folder structure. That will be visible in Xcode when you pull the code, but won't be visible in the code branch in github.

• I like the suggestion for the MojioClientEnvironment, but that will have to wait (as I need to do some reading around the best patterns achieve that)

**Pull request merged**
