### PR TITLE
Changes to phone number support for the SDK

### PR DESCRIPTION
**Pull request by agarwalashish**

### CODE REVIEW

**Comment by sureshven** [comment]
Use the requestParams dict instead of hard coding url parameters:

> if phone != nil && sendVerification == true {
>     phone = phone! + "?sendVerification=true"
> }

**Comment by agarwalashish** [comment]
I spent an hour trying that. It wasn't working and nobody from the API team was around to answer why

**Comment by sureshven** [comment]
runEncodeUrl is not for json-content - the headers are incorrect (encoding: .URL)
Also did runEncodeJSON changed from (encoding: .JSON to .Custom)?

**Comment by sureshven** [comment]
Alomofire  automatically inserts the correct request headers and encode parameters when the call is made. Get request params will be in the URL and post will be in the body as x-www-form-urlencoded.

**Comment by sureshven** [comment]
request.responseJSON will also insert the correct accept-type.

**Comment by agarwalashish** [comment]
Removed json header from runEncodeUrl. Not sure what the bug was, I tried sending the phone number verification request using Postman and x-www-form-urlencoded format, that did not work.

**Pull request merged**
