### PR TITLE
Feature/sureshv/mojio sdk objc compat

### PR DESCRIPTION
**Pull request by sureshven**

### CODE REVIEW

**Comment by sureshven** [comment]
TODO: We need to normalize Units, Severity Values, etc across the SDK's for 3rd Party Devs.

**Comment by agarwalashish** [comment]
Units returned by the API will always be the metric system - kms, litres, etc. The app developers will have to do the appropriate conversion to imperial units, etc

**Comment by agarwalashish** [comment]
It would be a good idea to document that in the SDK documentation however

**Comment by nothingmn** [comment]
Right now the API will return calls with those default units.  In the
future we hope to make it profile based. So clients should always be
checking Units and dealing with them accordingly.




On Mon, Apr 18, 2016 at 1:12 PM, agarwalashish <notifications@github.com>
wrote:

> It would be a good idea to document that in the SDK documentation however
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mojio/mojio-ios-sdk/pull/18#issuecomment-211555594>
>



-- 


{ Rob Chartier | ASPInsider | http://robchartier.*io*
<http://robchartier.io> | http://blog.robchartier.*io*
<http://blog.robchartier.io> | 604-338-2512 }

**Comment by agarwalashish** [comment]
Looks good.

**Comment by agarwalashish** [comment]
@nothingmn From an app developer's standpoint, I would say implementation is easier if all the units are metric units. That way, based on a user's locale (or any other criteria) it is much easier to convert it into imperial units. 

Whereas if we start returning API values based on profiles the number of checks we do on the front-end increase the complexity of the code and make it harder to write unit tests for all scenarios.

**Comment by sureshven** [comment]
I agree with @agarwalashish - let's normalize to metric and let the client handle the conversion if any (like sending date/time as UTC). Really it's the United States, Liberia, and Myanmar who are non-metric - wonderful company ;-).

**Pull request merged**
