### PR TITLE
Update to refresh token handling

### PR DESCRIPTION
**Pull request by sureshven**

### CODE REVIEW

**Comment by agarwalashish** [comment]
Is there a reason for moving from completion?(success: false) to failure(response: nil) ?

**Comment by sureshven** [comment]
The SDK pushes authToken handling to the client - so now refresh matches login (refresh cycle works the same). I'm not excited about the async approach but it's what we have until we can give it more thought.

**Comment by agarwalashish** [comment]
When you say client, I'm assuming you mean RestClient() ? The Motion part of the code should not be doing authToken handling at all.

**Comment by sureshven** [comment]
AuthClient handles refresh/login

**Comment by agarwalashish** [comment]
Ok, looks good. Feel free to merge

**Pull request merged**
