### PR TITLE
Parsing status code 201 messages

### PR DESCRIPTION
**Pull request by agarwalashish**

### CODE REVIEW

**Comment by sureshven** [comment]
> if let obj = self.parseDict(responseDict)

Do you want to check for nil?

**Comment by agarwalashish** [comment]
Yes, wouldn't the line handle that ?

**Comment by sureshven** [comment]
Yes - the if let will default to nil check when no type is specified for the let var..

Equal to if let obj : AnyObject = self.parseDict(responseDict)

This would always succeed if let obj : AnyObject? = self.parseDict(responseDict)

**Comment by sureshven** [comment]
Merge when ready

**Pull request merged**
